name: 'Merge Main to Sandbox'

on:
  push:
    branches:
      - main

jobs:
  mergeMainToSandbox:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Merge Main to Sandbox
        uses: robotology/gh-action-nightly-merge@v1.5.2
        with:
          stable_branch: 'main'
          development_branch: 'sandbox'
          allow_ff: true
          allow_forks: true
          user_name: GitHub Merge Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
